### ISSUE TITLE
Timeout Crash

### ISSUE THREAD

**Issue by Minibus50** [hsoft/dupeguru#487] opened 2018-02-21 11:10 UTC
Please note that dupeGuru is currently
[unmaintained](https://github.com/hsoft/dupeguru#current-status-unmaintained). That means that this
issue is unlikely to be answered in a timely manner.

Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse
  File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close
AttributeError: 'ProgressWindow' object has no attribute '_timer'

In Music mode searching over wireless lan I was referencing approx 30,000 files, 125Gb of data.

Windows folder chain was 5 folders deep and there were repeated same text errors like above.

**Comment by arsenetar** [comment] 2018-02-25 18:57
Duplicate of #449 which was fixed in #460. 4.0.4 will have this fixed.

**Closed** 2018-05-22 02:49 UTC
Labels: Windows
