### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_display_info'

### ISSUE THREAD

**Issue by johnfoxii** [hsoft/dupeguru#473] opened 2017-12-17 00:16 UTC
Error encountered while moving to another folder. 
I am using win 10 preview. Does the app drop a log somwhere? 

	
	Application Name: dupeGuru
	Version: 4.0.3

	Traceback (most recent call last):
	  File "C:\Users\arsen\github\dupeguru\qtlib\table.py", line 85, in data
	  File "C:\Users\arsen\github\dupeguru\qt\results_model.py", line 39, in _getData
	  File "C:\Users\arsen\github\dupeguru\core\gui\result_table.py", line 43, in is_cell_delta
	AttributeError: 'NoneType' object has no attribute 'get_display_info'

closing displayed:
	Application Name: dupeGuru
	Version: 4.0.3

	Traceback (most recent call last):
	  File "C:\Users\arsen\github\dupeguru\qtlib\table.py", line 83, in data
	  File "C:\Users\arsen\github\dupeguru\hscommon\gui\table.py", line 42, in __getitem__
	IndexError: list index out of range

	Without exiting I was able to rescan and move the rest of the files to trash.

**Comment by arsenetar** [comment] 2018-01-05 02:00
I'll take a look into this, you can get the debug log from the help menu in the application.

**Comment by hsoft** [comment] 2018-01-05 02:41
@arsenetar it's probably not windows-specific. This kind of traceback has been reported for a long time but it's hard to debug because it's an effect of an underlying cause which is hard to pinpoint without being able to reproduce locally (which I never could). good luck :)

**Comment by johnfoxii** [comment] 2018-01-14 03:37
The app has been working perfectly and the error has not happen again -  if
it does i will try and grab the stack.

I don't know if this is the proper way to make a suggestion -
I am using it to clean up duplicates in a music collection (does the best
job of the ten or so i have tried)
When using the delta values option  could the values that don't match
display differently that the ones that do?

Thank you again for you excellent app
-john

**Comment by Cebtenzzre** [comment] 2018-05-12 11:11
This is a dupe of #272, it should be closed.

**Comment by arsenetar** [comment] 2018-05-22 02:54
Closing duplicate

**Closed by arsenetar** 2018-05-22 02:54 UTC
