### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by AndrzejFelczak** [hsoft/dupeguru#486] opened 2018-02-17 20:20 UTC
Please note that dupeGuru is currently
[unmaintained](https://github.com/hsoft/dupeguru#current-status-unmaintained). That means that this
issue is unlikely to be answered in a timely manner.

Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse
  File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close
AttributeError: 'ProgressWindow' object has no attribute '_timer'

Error occurred while comparing 144 GB

**Comment by arsenetar** [comment] 2018-02-17 21:24
Duplicate of #449 which was fixed in #460. 4.0.4 will have this fixed.

**Closed by arsenetar** 2018-02-17 21:24 UTC
