### ISSUE TITLE
Error scanning picture contents on macOS Sierra

### ISSUE THREAD

**Issue by gryphonmyers** [hsoft/dupeguru#402] opened 2016-12-23 02:48 UTC
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.2 (Build 16C67)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:34821'

It does this whenever I add a folder then attempt to do a contents picture scan. It seems to be a 100% failure rate for me right now, but it did work somewhat recently so it's possible the most recent Sierra update broke something.

**Comment by buddymedbery** [comment] 2016-12-28 12:43
Similar problem - worked once, but not again after pruning some subfolders and re-arranging others

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.2 (Build 16C67)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: "path:/Volumes/Pegasus storage/Still images/Chuck's pics/Canadian Rockies:Glacier 2014/Glacier Grinnel Glacier Trail6.jpg"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b"path:/Volumes/Pegasus storage/Still images/Chuck's pics/Canadian Rockies:Glacier 2014/Glacier Grinnel Glacier Trail6.jpg"

**Comment by calonge9** [comment] 2017-01-28 11:50
Same problem.
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Versie 10.12.1 (build 16B2555)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b’id:105366'

**Comment by hsoft** [comment] 2017-05-06 17:09
I haven't spent a lot of time on this, but it isn't trivial to reproduce. A workaround would be easy to implement, but it would be better to find reliable steps to reproduce first.

**Comment by keithrokoske** [comment] 2017-08-07 23:35
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.6 (Build 16G29)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Volumes/Chloe/Transfer Archive ALL/DSCF0022 (1).JPG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Volumes/Chloe/Transfer Archive ALL/DSCF0022 (1).JPG'

**Comment by silentnyte** [comment] 2017-09-02 11:39
Same problem here. Worked the first time but now it won't work. Tried reinstalling, no go.

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.4 (Build 16E195)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Volumes/Local01/Pictures/2008/07/20080706_124659-5.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Volumes/Local01/Pictures/2008/07/20080706_124659-5.jpg'

**Comment by hsoft** [comment] 2017-10-08 20:47
These errors are probably all duplicates of #439, which should normally be fixed in v4.0.4.

**Closed by hsoft** 2017-10-08 20:47 UTC
Labels: bug
