### ISSUE TITLE
heres another

### ISSUE THREAD

**Issue by shugo83** [hsoft/dupeguru#303] opened 2015-04-16 17:13 UTC
```
Application Name: dupeGuru Picture Edition
Version: 2.10.1

Traceback (most recent call last):
  File "C:\src\dupeguru\qtlib\table.py", line 85, in data
  File "C:\src\dupeguru\qt\base\results_model.py", line 35, in _getData
  File "C:\src\dupeguru\core\gui\result_table.py", line 43, in is_cell_delta
AttributeError: 'NoneType' object has no attribute 'get_display_info'
```

**Comment by hsoft** [comment] 2015-04-16 22:06
Duplicate of #272 . Closing.

**Closed by hsoft** 2015-04-16 22:06 UTC
