### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Matttribal** [hsoft/dupeguru#467] opened 2017-12-01 18:37 UTC
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse
  File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close
AttributeError: 'ProgressWindow' object has no attribute '_timer'

**Comment by hsoft** [comment] 2017-12-01 20:08
Probably a duplicate of #449

**Closed by hsoft** 2017-12-01 20:08 UTC
