### ISSUE TITLE
Another crash error...

### ISSUE THREAD

**Issue by gordsellar** [hsoft/dupeguru#397] opened 2016-10-01 11:18 UTC
Not sure if this is the same as the others. I've often had crashes while scanning, and finally got tired of it and looked it up. Trying to scan as my hard drive is pretty full, not sure but maybe that has something to do with it?

Got this crash message when I tried to clear the Picture Cache (using the menu item in the File Menu).

`Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.1
Mac OS X Version: Version 10.10.5 (Build 14F1021)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 145, in property_valueAtPath_
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/tree.py", line 106, in children_count
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/directory_tree.py", line 27, in __len__
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/directory_tree.py", line 32, in _load
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 53, in get_subfolders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 53, in <listcomp>
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined
` 

Sure would be nice not to have crashes. Possible it was caused by my scanning huge amounts of files on multiple, very large drives? Not sure...

**Comment by hsoft** [comment] 2016-10-02 01:03
Probably a duplicate of #389

**Closed by hsoft** 2016-10-02 01:03 UTC
