### ISSUE TITLE
dupeGuru 4.0.1

### ISSUE THREAD

**Issue by pnn314** [hsoft/dupeguru#394] opened 2016-09-22 03:12 UTC
dupeGuru 4.0.1 does not work on macOS Sierra with pictures. It freezes.

**Comment by greck** [comment] 2016-09-23 22:20
I've had crashes on two different Sierra-running systems today; here are some details from one of them.

**Configuration**

* iMac (21.5-inch, Mid 2010)
* macOS Sierra 10.12
* dupeGuru 4.0.1

**Reproduction**

* Uninstall app, delete preferences
* Install 4.0.1, change no defaults
* Chose a directory to scan, use normal mode
* Select Picture, and Contents, and start scan
* During scanning, at "Performed 0/n chunk matches" an exception will occur

**Documentation**

Crash report and screenshot attached.

![dupeguru_4 0 1_on_sierra_crash](https://cloud.githubusercontent.com/assets/73836/18802953/0d07023e-81a1-11e6-88b7-d72805ffc2a1.png)
[dupeguru_4.0.1_on_sierra_crash.txt](https://github.com/hsoft/dupeguru/files/490774/dupeguru_4.0.1_on_sierra_crash.txt)

**Comment by hsoft** [comment] 2016-09-29 16:56
Sorry for the delay, I lack availability these days. It sounds like a bad problem, I'll look into it soon.

**Comment by greck** [comment] 2016-09-29 17:09
I feel the lack of availability; I'm about to go on vacation (finally) and hope to have free time when I get back, and will take a look myself if it's unresolved.

**Comment by hsoft** [comment] 2016-09-30 21:08
It looks like a tricky problems. The crash stack trace looks a lot like https://bugs.python.org/issue27126 , which has no resolution.

What I find strange is that the bug does not seem sierra-specific. Maybe that apple-suplied sqlite always caused random crashes, but that with sierra, they became systematic. I don't know.

A possible solution seems to be to ship with a private version of sqlite instead of linking to apple's. Another solution would be so implement and alternative implementation of `core.pe.cache.Cache` with a `shelve` backend.

**Comment by hsoft** [comment] 2016-10-01 16:56
I've made early tests with a the pre-compiled Python 3.5.2 that comes from python.org (the bug linked in my previous comment mentions that it's built with a private version of sqlite) and it fixes the crash. Previous dupeGuru builds are made with a locally compiled Python, and this one links to the system-provided sqlite.

This is, however, not an elegant solution. To have dupeGuru build properly, I had to fudge around with the python package to remove `i386` from sysconfig. Otherwise, I would get link errors.

That is, however, more fitting of a bugfix release than a completely new implementation of the picture cache.

So the plan would be to release a dupeGuru 4.0.2 with a fudged-around pre-compiled python and a dupeGuru 4.1 with a `shelve`-based picture cache. If that implementation is significantly slower than the sqlite version, it could be conditionally loaded (sqlite would be enabled on linux only).

**Comment by hsoft** [comment] 2016-10-06 00:43
I've created a test build and uploaded it at https://download.hardcoded.net/dupeguru_osx_4_0_1_sierra_test.dmg (pgp signature at https://download.hardcoded.net/dupeguru_osx_4_0_1_sierra_test.dmg.sig).

On my machine it fixed the crash. Can anyone confirm on their machine?

**Comment by hsoft** [comment] 2016-10-06 01:30
@pnn314 oops, sorry. It's fixed now.

**Comment by pnn314** [comment] 2016-10-06 01:46
Now it works OK on my iMac without freezing and crash.
Regards,
Nikolay

**Comment by what2be** [comment] 2016-10-06 20:26
Works for me now as well. Thank you!!!

**Comment by Vinfab** [comment] 2016-10-07 01:32
Its works now. No more crashes! Many thanks, JP

Configuration
	•	iMac (27-inch, Late 2014)
	•	macOS Sierra 10.12.1
	•	dupeGuru 4.0.1 Sierra test

**Comment by hsoft** [comment] 2016-10-07 13:15
Good, thanks for testing everyone. I'll release v4.0.2 soon.

**Comment by lekordable** [comment] 2016-10-07 16:43
Looks like I'm a bit late, but this fix also worked for me.

iMac 27 - Late 2013
3.2 GHz Intel Core i5
Mac OS 10.12 (16A323)

Thanks a bunch

**Comment by hsoft** [comment] 2016-10-11 03:11
Fixed in v4.0.2.

**Closed by hsoft** 2016-10-11 03:11 UTC
Labels: bug
