### ISSUE TITLE
Error Report DupeGuru

### ISSUE THREAD

**Issue by pboonyarat** [hsoft/dupeguru#499] opened 2018-04-25 09:00 UTC
It showed me like and i cannot close the window
what should i do with it?

Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse
  File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close
AttributeError: 'ProgressWindow' object has no attribute '_timer'

**Comment by arsenetar** [comment] 2018-05-22 02:48
Duplicate of #449 this will be fixed in the next release.

**Closed** 2018-05-22 02:48 UTC
