### ISSUE TITLE
Error #2 after moving to a specified folder

### ISSUE THREAD

**Issue by aramparonikyan-scdm** [hsoft/dupeguru#302] opened 2015-04-13 11:11 UTC
```
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "/usr/share/dupeguru_se/qtlib/table.py", line 83, in data
    row = self.model[index.row()]
  File "/usr/share/dupeguru_se/hscommon/gui/table.py", line 42, in __getitem__
    return self._rows.__getitem__(key)
IndexError: list index out of range
```

**Comment by hsoft** [comment] 2015-04-16 22:04
Did this happen while you re-tried moving after having experienced the error from #301?

**Comment by aram-paronikyan** [comment] 2015-04-20 20:37
Hi! The move operation suceeded along with hitting the error. That's why I couldn't retry.
Thanks!

**Comment by hsoft** [comment] 2015-04-20 20:56
The question was not whether you managed to reproduce the error. My question was:

Did this error happen right after the one you reported at #301 ?

If yes, it's probably just a byproduct of #301 and is not worth trying to fix because fixing #301 will fix this bug as well.

**Comment by aramparonikyan-scdm** [comment] 2015-04-21 10:32
Got it! 
Both errors were thrown at once - one after other. No action was made in the middle of their occurrence.

**Comment by hsoft** [comment] 2015-04-21 11:22
Thanks for the details. I'll close this ticket then, it's almost certain to be a simple byproduct of the first error.

**Closed by hsoft** 2015-04-21 11:22 UTC
Labels: bug, hold

**Comment by aramparonikyan-scdm** [comment] 2015-04-21 11:24
Sure! Thank you!

On Tue, Apr 21, 2015 at 3:22 PM, Virgil Dupras <notifications@github.com>
wrote:

> Thanks for the details. I'll close this ticket then, it's almost certain
> to be a simple byproduct of the first error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hsoft/dupeguru/issues/302#issuecomment-94752550>.
>

-- 
***********************************************************
This message may contain confidential and/or privileged 
information. If you are not the addressee or authorized to 
receive this for the addressee, you must not use, copy, 
disclose or take any action based on this message or any 
information herein. If you have received this message in 
error, please advise the sender immediately by reply e-mail 
and delete this message. Thank you for your cooperation.
***********************************************************
