### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by moehusni** [hsoft/dupeguru#475] opened 2018-01-08 10:43 UTC
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse
  File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close
AttributeError: 'ProgressWindow' object has no attribute '_timer'

**Comment by arsenetar** [comment] 2018-01-09 01:17
Possibly a duplicate of #449.

**Comment by arsenetar** [comment] 2018-02-17 21:25
Duplicate of #449 and fixed in #460.

**Closed by arsenetar** 2018-02-17 21:25 UTC
