### ISSUE TITLE
Error: name 'logging' is not defined

### ISSUE THREAD

**Issue by Donkard** [hsoft/dupeguru#419] opened 2017-03-31 13:27 UTC
Hi,
Anyone come across a solution to this error?
I can get back into the app without error messages popping up constantly so it's unusable right now.
Details below.
Many thanks.

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.8.5 (Build 12F2560)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 145, in property_valueAtPath_
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/tree.py", line 106, in children_count
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/directory_tree.py", line 27, in __len__
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/directory_tree.py", line 32, in _load
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 53, in get_subfolders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 53, in <listcomp>
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined

**Comment by hsoft** [comment] 2017-04-03 01:52
I don't think you're alone. It seems like a duplicate of #399 and/or #389. Closing.

**Closed by hsoft** 2017-04-03 01:52 UTC
