### ISSUE TITLE
Error after moving to a specified folder

### ISSUE THREAD

**Issue by aramparonikyan-scdm** [hsoft/dupeguru#301] opened 2015-04-13 11:10 UTC
```
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "/usr/share/dupeguru_se/qtlib/table.py", line 85, in data
    return self._getData(row, column, role)
  File "/usr/share/dupeguru_se/qt/base/results_model.py", line 35, in _getData
    elif row.is_cell_delta(column.name):
  File "/usr/share/dupeguru_se/core/gui/result_table.py", line 43, in is_cell_delta
    ref_info = self._group.ref.get_display_info(group=self._group, delta=False)
AttributeError: 'NoneType' object has no attribute 'get_display_info'
```

**Comment by hsoft** [comment] 2015-04-16 22:05
Duplicate of #272 . Closing.

**Closed by hsoft** 2015-04-16 22:05 UTC
